Issue #7
spring-for-hitchhiker/java-study pull request #22
Opened 2024-01-31 07:14 UTC by AreSain

과제 자료 및 질문 답변입니다.

2024-01-31 10:57 UTC, yhames requested changes
노션이 편하고 강력한 도구이지만, 글을 읽는 사람이 좀 더 편하게 읽을 수 있도록 하는 것이 좋다고 생각했습니다. 노션 로그인 없이 볼 수 있으면 좀 더 접근성이 좋을 것 같습니다!

2024-01-31 10:57 UTC, yhames commented on subject_07/과제_07.md
> +[https://www.notion.so/2-de673b70e811419aa01e257db0f072ed?pvs=4#47e5c2af846f4fa88282dc8c79b3c75b](https://www.notion.so/3-de673b70e811419aa01e257db0f072ed?pvs=21)
노션은 로그인 안하면 안보이네요..! 로그인 없이 볼 수 있었으면 좋겠습니다.

2024-01-31 10:57 UTC, yhames commented on subject_07/과제_07.md
> +[https://www.notion.so/2-de673b70e811419aa01e257db0f072ed?pvs=4#e0e6ab7ac1414029aa32dcfbfe497307](https://www.notion.so/3-de673b70e811419aa01e257db0f072ed?pvs=21)
노션은 로그인 안하면 안보이네요..! 로그인 없이 볼 수 있었으면 좋겠습니다.

2024-02-01 06:12 UTC, yhames approved these changes
고생하셨습니다!

2024-02-01 06:15 UTC, KenWR reviewed
정말 많이 정리하신걸 한눈에봐도 알수 있었습니다!

2024-02-01 11:37 UTC, ybs132 approved these changes

2024-02-08 22:03 UTC, merged